name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - run: pnpm run lint
      - run: pnpm test:cov
      - run: pnpm run build:release
        env:
          CI: true
          
      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: ./coverage/junit.xml
          coverage_format: TXT
          coverage_path: ./coverage/lcov.info
