name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm run lint
      - run: pnpm test:cov
      - run: pnpm run build:release
        env:
          CI: true
